export const COUNTRIES = [
    { label: "Afghanistan", value: 'Afghanistan', attrs: { disabled: false } },
    { label: "Åland Islands", value: 'Åland Islands', attrs: { disabled: false } },
    { label: "Albania", value: 'Albania', attrs: { disabled: false } },
    { label: "Algeria", value: 'Algeria', attrs: { disabled: false } },
    { label: "American Samoa", value: 'American Samoa', attrs: { disabled: false } },
    { label: "Andorra", value: 'Andorra', attrs: { disabled: false } },
    { label: "Angola", value: 'Angola', attrs: { disabled: false } },
    { label: "Anguilla", value: 'Anguilla', attrs: { disabled: false } },
    { label: "Antarctica", value: 'Antarctica', attrs: { disabled: false } },
    { label: "Antigua and Barbuda", value: 'Antigua and Barbuda', attrs: { disabled: false } },
    { label: "Argentina", value: 'Argentina', attrs: { disabled: false } },
    { label: "Armenia", value: 'Armenia', attrs: { disabled: false } },
    { label: "Aruba", value: 'Aruba', attrs: { disabled: false } },
    { label: "Australia", value: 'Australia', attrs: { disabled: false } },
    { label: "Austria", value: 'Austria', attrs: { disabled: false } },
    { label: "Azerbaijan", value: 'Azerbaijan', attrs: { disabled: false } },
    { label: "Bahamas", value: 'Bahamas', attrs: { disabled: false } },
    { label: "Bahrain", value: 'Bahrain', attrs: { disabled: false } },
    { label: "Bangladesh", value: 'Bangladesh', attrs: { disabled: false } },
    { label: "Barbados", value: 'Barbados', attrs: { disabled: false } },
    { label: "Belarus", value: 'Belarus', attrs: { disabled: false } },
    { label: "Belgium", value: 'Belgium', attrs: { disabled: false } },
    { label: "Belize", value: 'Belize', attrs: { disabled: false } },
    { label: "Benin", value: 'Benin', attrs: { disabled: false } },
    { label: "Bermuda", value: 'Bermuda', attrs: { disabled: false } },
    { label: "Bhutan", value: 'Bhutan', attrs: { disabled: false } },
    { label: "Bolivia", value: 'Bolivia', attrs: { disabled: false } },
    { label: "Bosnia and Herzegovina", value: 'Bosnia and Herzegovina', attrs: { disabled: false } },
    { label: "Botswana", value: 'Botswana', attrs: { disabled: false } },
    { label: "Bouvet Island", value: 'Bouvet Island', attrs: { disabled: false } },
    { label: "Brazil", value: 'Brazil', attrs: { disabled: false } },
    { label: "British Indian Ocean Territory", value: 'British Indian Ocean Territory', attrs: { disabled: false } },
    { label: "Brunei Darussalam", value: 'Brunei Darussalam', attrs: { disabled: false } },
    { label: "Bulgaria", value: 'Bulgaria', attrs: { disabled: false } },
    { label: "Burkina Faso", value: 'Burkina Faso', attrs: { disabled: false } },
    { label: "Burundi", value: 'Burundi', attrs: { disabled: false } },
    { label: "Cambodia", value: 'Cambodia', attrs: { disabled: false } },
    { label: "Cameroon", value: 'Cameroon', attrs: { disabled: false } },
    { label: "Canada", value: 'Canada', attrs: { disabled: false } },
    { label: "Cape Verde", value: 'Cape Verde', attrs: { disabled: false } },
    { label: "Cayman Islands", value: 'Cayman Islands', attrs: { disabled: false } },
    { label: "Central African Republic", value: 'Central African Republic', attrs: { disabled: false } },
    { label: "Chad", value: 'Chad', attrs: { disabled: false } },
    { label: "Chile", value: 'Chile', attrs: { disabled: false } },
    { label: "China", value: 'China', attrs: { disabled: false } },
    { label: "Christmas Island", value: 'Christmas Island', attrs: { disabled: false } },
    { label: "Cocos (Keeling) Islands", value: 'Cocos (Keeling) Islands', attrs: { disabled: false } },
    { label: "Colombia", value: 'Colombia', attrs: { disabled: false } },
    { label: "Comoros", value: 'Comoros', attrs: { disabled: false } },
    { label: "Congo", value: 'Congo', attrs: { disabled: false } },
    { label: "Congo, The Democratic Republic of The", value: 'Congo, The Democratic Republic of The', attrs: { disabled: false } },
    { label: "Cook Islands", value: 'Cook Islands', attrs: { disabled: false } },
    { label: "Costa Rica", value: 'Costa Rica', attrs: { disabled: false } },
    { label: "Cote D'ivoire", value: "Cote D'ivoire", attrs: { disabled: false } },
    { label: "Croatia", value: 'Croatia', attrs: { disabled: false } },
    { label: "Cuba", value: 'Cuba', attrs: { disabled: false } },
    { label: "Cyprus", value: 'Cyprus', attrs: { disabled: false } },
    { label: "Czech Republic", value: 'Czech Republic', attrs: { disabled: false } },
    { label: "Denmark", value: 'Denmark', attrs: { disabled: false } },
    { label: "Djibouti", value: 'Djibouti', attrs: { disabled: false } },
    { label: "Dominica", value: 'Dominica', attrs: { disabled: false } },
    { label: "Dominican Republic", value: 'Dominican Republic', attrs: { disabled: false } },
    { label: "Ecuador", value: 'Ecuador', attrs: { disabled: false } },
    { label: "Egypt", value: 'Egypt', attrs: { disabled: false } },
    { label: "El Salvador", value: 'El Salvador', attrs: { disabled: false } },
    { label: "Equatorial Guinea", value: 'Equatorial Guinea', attrs: { disabled: false } },
    { label: "Eritrea", value: 'Eritrea', attrs: { disabled: false } },
    { label: "Estonia", value: 'Estonia', attrs: { disabled: false } },
    { label: "Ethiopia", value: 'Ethiopia', attrs: { disabled: false } },
    { label: "Falkland Islands (Malvinas)", value: 'Falkland Islands (Malvinas)', attrs: { disabled: false } },
    { label: "Faroe Islands", value: 'Faroe Islands', attrs: { disabled: false } },
    { label: "Fiji", value: 'Fiji', attrs: { disabled: false } },
    { label: "Finland", value: 'Finland', attrs: { disabled: false } },
    { label: "France", value: 'France', attrs: { disabled: false } },
    { label: "French Guiana", value: 'French Guiana', attrs: { disabled: false } },
    { label: "French Polynesia", value: 'French Polynesia', attrs: { disabled: false } },
    { label: "French Southern Territories", value: 'French Southern Territories', attrs: { disabled: false } },
    { label: "Gabon", value: 'Gabon', attrs: { disabled: false } },
    { label: "Gambia", value: 'Gambia', attrs: { disabled: false } },
    { label: "Georgia", value: 'Georgia', attrs: { disabled: false } },
    { label: "Germany", value: 'Germany', attrs: { disabled: false } },
    { label: "Ghana", value: 'Ghana', attrs: { disabled: false } },
    { label: "Gibraltar", value: 'Gibraltar', attrs: { disabled: false } },
    { label: "Greece", value: 'Greece', attrs: { disabled: false } },
    { label: "Greenland", value: 'Greenland', attrs: { disabled: false } },
    { label: "Grenada", value: 'Grenada', attrs: { disabled: false } },
    { label: "Guadeloupe", value: 'Guadeloupe', attrs: { disabled: false } },
    { label: "Guam", value: 'Guam', attrs: { disabled: false } },
    { label: "Guatemala", value: 'Guatemala', attrs: { disabled: false } },
    { label: "Guernsey", value: 'Guernsey', attrs: { disabled: false } },
    { label: "Guinea", value: 'Guinea', attrs: { disabled: false } },
    { label: "Guinea-bissau", value: 'Guinea-bissau', attrs: { disabled: false } },
    { label: "Guyana", value: 'Guyana', attrs: { disabled: false } },
    { label: "Haiti", value: 'Haiti', attrs: { disabled: false } },
    { label: "Heard Island and Mcdonald Islands", value: 'Heard Island and Mcdonald Islands', attrs: { disabled: false } },
    { label: "Holy See (Vatican City State)", value: 'Holy See (Vatican City State)', attrs: { disabled: false } },
    { label: "Honduras", value: 'Honduras', attrs: { disabled: false } },
    { label: "Hong Kong", value: 'Hong Kong', attrs: { disabled: false } },
    { label: "Hungary", value: 'Hungary', attrs: { disabled: false } },
    { label: "Iceland", value: 'Iceland', attrs: { disabled: false } },
    { label: "India", value: 'India', attrs: { disabled: false } },
    { label: "Indonesia", value: 'Indonesia', attrs: { disabled: false } },
    { label: "Iran, Islamic Republic of", value: 'Iran, Islamic Republic of', attrs: { disabled: false } },
    { label: "Iraq", value: 'Iraq', attrs: { disabled: false } },
    { label: "Ireland", value: 'Ireland', attrs: { disabled: false } },
    { label: "Isle of Man", value: 'Isle of Man', attrs: { disabled: false } },
    { label: "Israel", value: 'Israel', attrs: { disabled: false } },
    { label: "Italy", value: 'Italy', attrs: { disabled: false } },
    { label: "Jamaica", value: 'Jamaica', attrs: { disabled: false } },
    { label: "Japan", value: 'Japan', attrs: { disabled: false } },
    { label: "Jersey", value: 'Jersey', attrs: { disabled: false } },
    { label: "Jordan", value: 'Jordan', attrs: { disabled: false } },
    { label: "Kazakhstan", value: 'Kazakhstan', attrs: { disabled: false } },
    { label: "Kenya", value: 'Kenya', attrs: { disabled: false } },
    { label: "Kiribati", value: 'Kiribati', attrs: { disabled: false } },
    { label: "Korea, Democratic People's Republic of", value: "Korea, Democratic People's Republic of", attrs: { disabled: false } },
    { label: "Korea, Republic of", value: 'Korea, Republic of', attrs: { disabled: false } },
    { label: "Kuwait", value: 'Kuwait', attrs: { disabled: false } },
    { label: "Kyrgyzstan", value: 'Kyrgyzstan', attrs: { disabled: false } },
    { label: "Lao People's Democratic Republic", value: "Lao People's Democratic Republic", attrs: { disabled: false } },
    { label: "Latvia", value: 'Latvia', attrs: { disabled: false } },
    { label: "Lebanon", value: 'Lebanon', attrs: { disabled: false } },
    { label: "Lesotho", value: 'Lesotho', attrs: { disabled: false } },
    { label: "Liberia", value: 'Liberia', attrs: { disabled: false } },
    { label: "Libyan Arab Jamahiriya", value: 'Libyan Arab Jamahiriya', attrs: { disabled: false } },
    { label: "Liechtenstein", value: 'Liechtenstein', attrs: { disabled: false } },
    { label: "Lithuania", value: 'Lithuania', attrs: { disabled: false } },
    { label: "Luxembourg", value: 'Luxembourg', attrs: { disabled: false } },
    { label: "Macao", value: 'Macao', attrs: { disabled: false } },
    { label: "Macedonia, The Former Yugoslav Republic of", value: 'Macedonia, The Former Yugoslav Republic of', attrs: { disabled: false } },
    { label: "Madagascar", value: 'Madagascar', attrs: { disabled: false } },
    { label: "Malawi", value: 'Malawi', attrs: { disabled: false } },
    { label: "Malaysia", value: 'Malaysia', attrs: { disabled: false } },
    { label: "Maldives", value: 'Maldives', attrs: { disabled: false } },
    { label: "Mali", value: 'Mali', attrs: { disabled: false } },
    { label: "Malta", value: 'Malta', attrs: { disabled: false } },
    { label: "Marshall Islands", value: 'Marshall Islands', attrs: { disabled: false } },
    { label: "Martinique", value: 'Martinique', attrs: { disabled: false } },
    { label: "Mauritania", value: 'Mauritania', attrs: { disabled: false } },
    { label: "Mauritius", value: 'Mauritius', attrs: { disabled: false } },
    { label: "Mayotte", value: 'Mayotte', attrs: { disabled: false } },
    { label: "Mexico", value: 'Mexico', attrs: { disabled: false } },
    { label: "Micronesia, Federated States of", value: 'Micronesia, Federated States of', attrs: { disabled: false } },
    { label: "Moldova, Republic of", value: 'Moldova, Republic of', attrs: { disabled: false } },
    { label: "Monaco", value: 'Monaco', attrs: { disabled: false } },
    { label: "Mongolia", value: 'Mongolia', attrs: { disabled: false } },
    { label: "Montenegro", value: 'Montenegro', attrs: { disabled: false } },
    { label: "Montserrat", value: 'Montserrat', attrs: { disabled: false } },
    { label: "Morocco", value: 'Morocco', attrs: { disabled: false } },
    { label: "Mozambique", value: 'Mozambique', attrs: { disabled: false } },
    { label: "Myanmar", value: 'Myanmar', attrs: { disabled: false } },
    { label: "Namibia", value: 'Namibia', attrs: { disabled: false } },
    { label: "Nauru", value: 'Nauru', attrs: { disabled: false } },
    { label: "Nepal", value: 'Nepal', attrs: { disabled: false } },
    { label: "Netherlands", value: 'Netherlands', attrs: { disabled: false } },
    { label: "Netherlands Antilles", value: 'Netherlands Antilles', attrs: { disabled: false } },
    { label: "New Caledonia", value: 'New Caledonia', attrs: { disabled: false } },
    { label: "New Zealand", value: 'New Zealand', attrs: { disabled: false } },
    { label: "Nicaragua", value: 'Nicaragua', attrs: { disabled: false } },
    { label: "Niger", value: 'Niger', attrs: { disabled: false } },
    { label: "Nigeria", value: 'Nigeria', attrs: { disabled: false } },
    { label: "Niue", value: 'Niue', attrs: { disabled: false } },
    { label: "Norfolk Island", value: 'Norfolk Island', attrs: { disabled: false } },
    { label: "Northern Mariana Islands", value: 'Northern Mariana Islands', attrs: { disabled: false } },
    { label: "Norway", value: 'Norway', attrs: { disabled: false } },
    { label: "Oman", value: 'Oman', attrs: { disabled: false } },
    { label: "Pakistan", value: 'Pakistan', attrs: { disabled: false } },
    { label: "Palau", value: 'Palau', attrs: { disabled: false } },
    { label: "Palestinian Territory, Occupied", value: 'Palestinian Territory, Occupied', attrs: { disabled: false } },
    { label: "Panama", value: 'Panama', attrs: { disabled: false } },
    { label: "Papua New Guinea", value: 'Papua New Guinea', attrs: { disabled: false } },
    { label: "Paraguay", value: 'Paraguay', attrs: { disabled: false } },
    { label: "Peru", value: 'Peru', attrs: { disabled: false } },
    { label: "Philippines", value: 'Philippines', attrs: { disabled: false } },
    { label: "Pitcairn", value: 'Pitcairn', attrs: { disabled: false } },
    { label: "Poland", value: 'Poland', attrs: { disabled: false } },
    { label: "Portugal", value: 'Portugal', attrs: { disabled: false } },
    { label: "Puerto Rico", value: 'Puerto Rico', attrs: { disabled: false } },
    { label: "Qatar", value: 'Qatar', attrs: { disabled: false } },
    { label: "Reunion", value: 'Reunion', attrs: { disabled: false } },
    { label: "Romania", value: 'Romania', attrs: { disabled: false } },
    { label: "Russian Federation", value: 'Russian Federation', attrs: { disabled: false } },
    { label: "Rwanda", value: 'Rwanda', attrs: { disabled: false } },
    { label: "Saint Helena", value: 'Saint Helena', attrs: { disabled: false } },
    { label: "Saint Kitts and Nevis", value: 'Saint Kitts and Nevis', attrs: { disabled: false } },
    { label: "Saint Lucia", value: 'Saint Lucia', attrs: { disabled: false } },
    { label: "Saint Pierre and Miquelon", value: 'Saint Pierre and Miquelon', attrs: { disabled: false } },
    { label: "Saint Vincent and The Grenadines", value: 'Saint Vincent and The Grenadines', attrs: { disabled: false } },
    { label: "Samoa", value: 'Samoa', attrs: { disabled: false } },
    { label: "San Marino", value: 'San Marino', attrs: { disabled: false } },
    { label: "Sao Tome and Principe", value: 'Sao Tome and Principe', attrs: { disabled: false } },
    { label: "Saudi Arabia", value: 'Saudi Arabia', attrs: { disabled: false } },
    { label: "Senegal", value: 'Senegal', attrs: { disabled: false } },
    { label: "Serbia", value: 'Serbia', attrs: { disabled: false } },
    { label: "Seychelles", value: 'Seychelles', attrs: { disabled: false } },
    { label: "Sierra Leone", value: 'Sierra Leone', attrs: { disabled: false } },
    { label: "Singapore", value: 'Singapore', attrs: { disabled: false } },
    { label: "Slovakia", value: 'Slovakia', attrs: { disabled: false } },
    { label: "Slovenia", value: 'Slovenia', attrs: { disabled: false } },
    { label: "Solomon Islands", value: 'Solomon Islands', attrs: { disabled: false } },
    { label: "Somalia", value: 'Somalia', attrs: { disabled: false } },
    { label: "South Africa", value: 'South Africa', attrs: { disabled: false } },
    { label: "South Georgia and The South Sandwich Islands", value: 'South Georgia and The South Sandwich Islands', attrs: { disabled: false } },
    { label: "Spain", value: 'Spain', attrs: { disabled: false } },
    { label: "Sri Lanka", value: 'Sri Lanka', attrs: { disabled: false } },
    { label: "Sudan", value: 'Sudan', attrs: { disabled: false } },
    { label: "Suriname", value: 'Suriname', attrs: { disabled: false } },
    { label: "Svalbard and Jan Mayen", value: 'Svalbard and Jan Mayen', attrs: { disabled: false } },
    { label: "Swaziland", value: 'Swaziland', attrs: { disabled: false } },
    { label: "Sweden", value: 'Sweden', attrs: { disabled: false } },
    { label: "Switzerland", value: 'Switzerland', attrs: { disabled: false } },
    { label: "Syrian Arab Republic", value: 'Syrian Arab Republic', attrs: { disabled: false } },
    { label: "Taiwan", value: 'Taiwan', attrs: { disabled: false } },
    { label: "Tajikistan", value: 'Tajikistan', attrs: { disabled: false } },
    { label: "Tanzania, United Republic of", value: 'Tanzania, United Republic of', attrs: { disabled: false } },
    { label: "Thailand", value: 'Thailand', attrs: { disabled: false } },
    { label: "Timor-leste", value: 'Timor-leste', attrs: { disabled: false } },
    { label: "Togo", value: 'Togo', attrs: { disabled: false } },
    { label: "Tokelau", value: 'Tokelau', attrs: { disabled: false } },
    { label: "Tonga", value: 'Tonga', attrs: { disabled: false } },
    { label: "Trinidad and Tobago", value: 'Trinidad and Tobago', attrs: { disabled: false } },
    { label: "Tunisia", value: 'Tunisia', attrs: { disabled: false } },
    { label: "Turkey", value: 'Turkey', attrs: { disabled: false } },
    { label: "Turkmenistan", value: 'Turkmenistan', attrs: { disabled: false } },
    { label: "Turks and Caicos Islands", value: 'Turks and Caicos Islands', attrs: { disabled: false } },
    { label: "Tuvalu", value: 'Tuvalu', attrs: { disabled: false } },
    { label: "Uganda", value: 'Uganda', attrs: { disabled: false } },
    { label: "Ukraine", value: 'Ukraine', attrs: { disabled: false } },
    { label: "United Arab Emirates", value: 'United Arab Emirates', attrs: { disabled: false } },
    { label: "United Kingdom", value: 'United Kingdom', attrs: { disabled: false } },
    { label: "United States", value: 'United States', attrs: { disabled: false } },
    { label: "United States Minor Outlying Islands", value: 'United States Minor Outlying Islands', attrs: { disabled: false } },
    { label: "Uruguay", value: 'Uruguay', attrs: { disabled: false } },
    { label: "Uzbekistan", value: 'Uzbekistan', attrs: { disabled: false } },
    { label: "Vanuatu", value: 'Vanuatu', attrs: { disabled: false } },
    { label: "Venezuela", value: 'Venezuela', attrs: { disabled: false } },
    { label: "Viet Nam", value: 'Viet Nam', attrs: { disabled: false } },
    { label: "Virgin Islands, British", value: 'Virgin Islands, British', attrs: { disabled: false } },
    { label: "Virgin Islands, U.S.", value: 'Virgin Islands, U.S.', attrs: { disabled: false } },
    { label: "Wallis and Futuna", value: 'Wallis and Futuna', attrs: { disabled: false } },
    { label: "Western Sahara", value: 'Western Sahara', attrs: { disabled: false } },
    { label: "Yemen", value: 'Yemen', attrs: { disabled: false } },
    { label: "Zambia", value: 'Zambia', attrs: { disabled: false } },
    { label: "Zimbabwe", value: 'Zimbabwe', attrs: { disabled: false } },
]